import {
  ExerciseDifficulty,
  ExerciseEquipment,
  ExerciseMuscleGroup,
  ExerciseType,
  type Exercise,
} from '../model/types';
import type {
  CreateExerciseParams,
  DeleteExercisesParams,
  DeleteExercisesResponse,
  FetchExercisesParams,
  FetchExercisesResponse,
} from './exercises.types';
import { filterExercisesByName } from './exercises.utils';
import { EXERCISE_RU } from './exercises.ru';

const MOCK_DELAY_MS = 400;
const MOCK_EXERCISES_COUNT = 120;

type SeedExercise = Omit<Exercise, 'nameRu' | 'descriptionRu'>;

const seedExercisesBase: SeedExercise[] = [
  {
    id: 'ex-001',
    name: 'Back Squat',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-05-20T10:12:00.000Z',
    equipment: ExerciseEquipment.SquatRack,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Barbell squat pattern focused on lower-body strength and trunk bracing.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/back-squat.mp4',
    previewImageUrl: 'https://example.com/images/back-squat.jpg',
  },
  {
    id: 'ex-002',
    name: 'Deadlift',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-05-19T14:24:00.000Z',
    equipment: ExerciseEquipment.Barbell,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Heavy hip-hinge lift for posterior-chain strength.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/deadlift.mp4',
    previewImageUrl: 'https://example.com/images/deadlift.jpg',
  },
  {
    id: 'ex-003',
    name: 'Bench Press',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-05-18T09:30:00.000Z',
    equipment: ExerciseEquipment.Barbell,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Chest,
    description: 'Horizontal press variation for chest, shoulders, and triceps.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/bench-press.mp4',
    previewImageUrl: 'https://example.com/images/bench-press.jpg',
  },
  {
    id: 'ex-004',
    name: 'Strict Pull-up',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-05-17T16:45:00.000Z',
    equipment: ExerciseEquipment.PullUpBar,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Back,
    description: 'Bodyweight vertical pull with controlled full-range reps.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/strict-pull-up.mp4',
    previewImageUrl: 'https://example.com/images/strict-pull-up.jpg',
  },
  {
    id: 'ex-005',
    name: 'Kettlebell Swing',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-05-16T11:20:00.000Z',
    equipment: ExerciseEquipment.Kettlebell,
    type: ExerciseType.Metcon,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Explosive hip extension drill for conditioning and power.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/kettlebell-swing.mp4',
    previewImageUrl: 'https://example.com/images/kettlebell-swing.jpg',
  },
  {
    id: 'ex-006',
    name: 'Row Erg Sprint',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-05-15T08:10:00.000Z',
    equipment: ExerciseEquipment.RowingMachine,
    type: ExerciseType.Intervals,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Short high-output rowing intervals with full recovery.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/row-erg-sprint.mp4',
    previewImageUrl: 'https://example.com/images/row-erg-sprint.jpg',
  },
  {
    id: 'ex-007',
    name: 'Assault Bike Calories',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-05-14T13:05:00.000Z',
    equipment: ExerciseEquipment.AssaultBike,
    type: ExerciseType.Cardio,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Cyclical conditioning effort using arms and legs together.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/assault-bike-calories.mp4',
    previewImageUrl: 'https://example.com/images/assault-bike-calories.jpg',
  },
  {
    id: 'ex-008',
    name: 'Double-under',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-05-13T15:50:00.000Z',
    equipment: ExerciseEquipment.JumpRope,
    type: ExerciseType.SkillWork,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Jump rope skill where the rope passes twice per jump.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/double-under.mp4',
    previewImageUrl: 'https://example.com/images/double-under.jpg',
  },
  {
    id: 'ex-009',
    name: 'Box Jump',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-05-12T12:33:00.000Z',
    equipment: ExerciseEquipment.PlyoBox,
    type: ExerciseType.MixedModal,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Explosive jump to a stable box with controlled step-down.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/box-jump.mp4',
    previewImageUrl: 'https://example.com/images/box-jump.jpg',
  },
  {
    id: 'ex-010',
    name: 'Wall Ball Shot',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-05-11T10:28:00.000Z',
    equipment: ExerciseEquipment.WallBall,
    type: ExerciseType.Metcon,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Squat and throw pattern performed to a wall target.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/wall-ball-shot.mp4',
    previewImageUrl: 'https://example.com/images/wall-ball-shot.jpg',
  },
  {
    id: 'ex-011',
    name: 'Medicine Ball Slam',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-05-10T17:15:00.000Z',
    equipment: ExerciseEquipment.MedicineBall,
    type: ExerciseType.MixedModal,
    muscleGroup: ExerciseMuscleGroup.Core,
    description: 'Powerful overhead slam emphasizing trunk flexion and control.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/medicine-ball-slam.mp4',
    previewImageUrl: 'https://example.com/images/medicine-ball-slam.jpg',
  },
  {
    id: 'ex-012',
    name: 'Band Face Pull',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-05-09T09:11:00.000Z',
    equipment: ExerciseEquipment.ResistanceBands,
    type: ExerciseType.Accessory,
    muscleGroup: ExerciseMuscleGroup.Shoulders,
    description: 'Upper-back accessory drill for scapular control and shoulder health.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/band-face-pull.mp4',
    previewImageUrl: 'https://example.com/images/band-face-pull.jpg',
  },
  {
    id: 'ex-013',
    name: 'Battle Rope Waves',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-05-08T15:44:00.000Z',
    equipment: ExerciseEquipment.BattleRopes,
    type: ExerciseType.Intervals,
    muscleGroup: ExerciseMuscleGroup.Arms,
    description: 'Repeated rope waves for upper-body conditioning.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/battle-rope-waves.mp4',
    previewImageUrl: 'https://example.com/images/battle-rope-waves.jpg',
  },
  {
    id: 'ex-014',
    name: 'Ring Row',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-05-07T11:02:00.000Z',
    equipment: ExerciseEquipment.GymnasticRings,
    type: ExerciseType.Accessory,
    muscleGroup: ExerciseMuscleGroup.Back,
    description: 'Scalable horizontal pull using rings and body angle.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/ring-row.mp4',
    previewImageUrl: 'https://example.com/images/ring-row.jpg',
  },
  {
    id: 'ex-015',
    name: 'Sandbag Clean',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-05-06T18:22:00.000Z',
    equipment: ExerciseEquipment.Sandbag,
    type: ExerciseType.MixedModal,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Odd-object clean from floor to shoulder with bracing emphasis.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/sandbag-clean.mp4',
    previewImageUrl: 'https://example.com/images/sandbag-clean.jpg',
  },
  {
    id: 'ex-016',
    name: 'Sled Push',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-05-05T07:40:00.000Z',
    equipment: ExerciseEquipment.Sled,
    type: ExerciseType.Metcon,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Loaded prowler push for leg drive and conditioning.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/sled-push.mp4',
    previewImageUrl: 'https://example.com/images/sled-push.jpg',
  },
  {
    id: 'ex-017',
    name: 'Plate Ground-to-Overhead',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-05-04T13:19:00.000Z',
    equipment: ExerciseEquipment.WeightPlates,
    type: ExerciseType.Metcon,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Plate movement from floor to locked-out overhead position.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/plate-ground-to-overhead.mp4',
    previewImageUrl: 'https://example.com/images/plate-ground-to-overhead.jpg',
  },
  {
    id: 'ex-018',
    name: 'Dumbbell Snatch',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-05-03T12:08:00.000Z',
    equipment: ExerciseEquipment.Dumbbells,
    type: ExerciseType.MixedModal,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Single-arm dumbbell pull from floor to overhead lockout.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/dumbbell-snatch.mp4',
    previewImageUrl: 'https://example.com/images/dumbbell-snatch.jpg',
  },
  {
    id: 'ex-019',
    name: 'Turkish Get-up',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-05-02T16:10:00.000Z',
    equipment: ExerciseEquipment.Kettlebell,
    type: ExerciseType.SkillWork,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Controlled floor-to-standing pattern with overhead stability.',
    difficulty: ExerciseDifficulty.Expert,
    videoUrl: 'https://example.com/videos/turkish-get-up.mp4',
    previewImageUrl: 'https://example.com/images/turkish-get-up.jpg',
  },
  {
    id: 'ex-020',
    name: 'Pigeon Stretch',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-05-01T09:55:00.000Z',
    equipment: ExerciseEquipment.ResistanceBands,
    type: ExerciseType.Stretching,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Hip external rotation stretch for cooldown and mobility blocks.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/pigeon-stretch.mp4',
    previewImageUrl: 'https://example.com/images/pigeon-stretch.jpg',
  },
  {
    id: 'ex-021',
    name: 'Front Rack Lunge',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-04-30T10:05:00.000Z',
    equipment: ExerciseEquipment.Barbell,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Loaded unilateral lunge from the front rack position.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/front-rack-lunge.mp4',
    previewImageUrl: 'https://example.com/images/front-rack-lunge.jpg',
  },
  {
    id: 'ex-022',
    name: 'Handstand Hold',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-04-29T14:42:00.000Z',
    equipment: ExerciseEquipment.GymnasticRings,
    type: ExerciseType.SkillWork,
    muscleGroup: ExerciseMuscleGroup.Shoulders,
    description: 'Static inverted hold for overhead balance and bodyline strength.',
    difficulty: ExerciseDifficulty.Expert,
    videoUrl: 'https://example.com/videos/handstand-hold.mp4',
    previewImageUrl: 'https://example.com/images/handstand-hold.jpg',
  },
  {
    id: 'ex-023',
    name: 'Farmer Carry',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-04-28T08:25:00.000Z',
    equipment: ExerciseEquipment.Dumbbells,
    type: ExerciseType.Accessory,
    muscleGroup: ExerciseMuscleGroup.Core,
    description: 'Loaded carry for grip, trunk stiffness, and posture.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/farmer-carry.mp4',
    previewImageUrl: 'https://example.com/images/farmer-carry.jpg',
  },
  {
    id: 'ex-024',
    name: 'Thruster',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-04-27T15:12:00.000Z',
    equipment: ExerciseEquipment.Barbell,
    type: ExerciseType.Metcon,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Front squat into overhead press performed as one continuous movement.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/thruster.mp4',
    previewImageUrl: 'https://example.com/images/thruster.jpg',
  },
  {
    id: 'ex-025',
    name: 'Burpee Box Jump-over',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-04-26T11:17:00.000Z',
    equipment: ExerciseEquipment.PlyoBox,
    type: ExerciseType.MixedModal,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Floor-to-box conditioning movement often used in metcons.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/burpee-box-jump-over.mp4',
    previewImageUrl: 'https://example.com/images/burpee-box-jump-over.jpg',
  },
  {
    id: 'ex-026',
    name: 'Hollow Hold',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-03',
    modifiedAt: '2026-04-25T09:48:00.000Z',
    equipment: ExerciseEquipment.ResistanceBands,
    type: ExerciseType.Accessory,
    muscleGroup: ExerciseMuscleGroup.Core,
    description: 'Static midline drill for trunk tension and body position.',
    difficulty: ExerciseDifficulty.Beginner,
    videoUrl: 'https://example.com/videos/hollow-hold.mp4',
    previewImageUrl: 'https://example.com/images/hollow-hold.jpg',
  },
  {
    id: 'ex-027',
    name: 'Ring Muscle-up',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-04-24T16:36:00.000Z',
    equipment: ExerciseEquipment.GymnasticRings,
    type: ExerciseType.SkillWork,
    muscleGroup: ExerciseMuscleGroup.Compound,
    description: 'Advanced ring pull-to-dip transition with strict or kipping options.',
    difficulty: ExerciseDifficulty.Expert,
    videoUrl: 'https://example.com/videos/ring-muscle-up.mp4',
    previewImageUrl: 'https://example.com/images/ring-muscle-up.jpg',
  },
  {
    id: 'ex-028',
    name: 'Sled Drag',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-04-23T13:01:00.000Z',
    equipment: ExerciseEquipment.Sled,
    type: ExerciseType.Cardio,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Backward or forward drag for leg stamina and knee-friendly loading.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/sled-drag.mp4',
    previewImageUrl: 'https://example.com/images/sled-drag.jpg',
  },
  {
    id: 'ex-029',
    name: 'Push Press',
    addedBy: 'Alex Ivanov',
    modifiedBy: 'coach-07',
    modifiedAt: '2026-04-22T10:34:00.000Z',
    equipment: ExerciseEquipment.Barbell,
    type: ExerciseType.Strength,
    muscleGroup: ExerciseMuscleGroup.Shoulders,
    description: 'Dip-drive overhead press that develops power transfer.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/push-press.mp4',
    previewImageUrl: 'https://example.com/images/push-press.jpg',
  },
  {
    id: 'ex-030',
    name: 'Cossack Squat',
    addedBy: 'Maria Petrova',
    modifiedBy: 'coach-19',
    modifiedAt: '2026-04-21T12:58:00.000Z',
    equipment: ExerciseEquipment.Kettlebell,
    type: ExerciseType.Stretching,
    muscleGroup: ExerciseMuscleGroup.Legs,
    description: 'Lateral squat pattern for adductor strength and hip mobility.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/cossack-squat.mp4',
    previewImageUrl: 'https://example.com/images/cossack-squat.jpg',
  },
  {
    id: 'ex-031',
    name: 'Rope Slam to Sprint',
    addedBy: 'Anna Kuznetsova',
    modifiedBy: 'coach-21',
    modifiedAt: '2026-04-20T08:03:00.000Z',
    equipment: ExerciseEquipment.BattleRopes,
    type: ExerciseType.Intervals,
    muscleGroup: ExerciseMuscleGroup.FullBody,
    description: 'Upper-body rope interval paired with short acceleration work.',
    difficulty: ExerciseDifficulty.Advanced,
    videoUrl: 'https://example.com/videos/rope-slam-to-sprint.mp4',
    previewImageUrl: 'https://example.com/images/rope-slam-to-sprint.jpg',
  },
  {
    id: 'ex-032',
    name: 'Weighted Plank',
    addedBy: 'Sergey Smirnov',
    modifiedBy: 'coach-12',
    modifiedAt: '2026-04-19T14:07:00.000Z',
    equipment: ExerciseEquipment.WeightPlates,
    type: ExerciseType.Accessory,
    muscleGroup: ExerciseMuscleGroup.Core,
    description: 'Anti-extension core hold loaded with a weight plate.',
    difficulty: ExerciseDifficulty.Intermediate,
    videoUrl: 'https://example.com/videos/weighted-plank.mp4',
    previewImageUrl: 'https://example.com/images/weighted-plank.jpg',
  },
];

const seedExercises: Exercise[] = seedExercisesBase.map((exercise) => ({
  ...exercise,
  ...(EXERCISE_RU[exercise.id] ?? { nameRu: exercise.name, descriptionRu: exercise.description }),
}));

const getSeedExercise = (index: number): Exercise => {
  const exercise = seedExercises[index % seedExercises.length];
  if (exercise) return exercise;

  throw new Error('Exercise seed data is empty.');
};

const mockExercises: Exercise[] = Array.from({ length: MOCK_EXERCISES_COUNT }, (_, index) => {
  const base = getSeedExercise(index);
  if (index < seedExercises.length) return base;

  const copyNumber = Math.floor(index / seedExercises.length) + 1;
  const modifiedAt = new Date(base.modifiedAt);
  modifiedAt.setDate(modifiedAt.getDate() - index);

  return {
    ...base,
    id: `ex-${String(index + 1).padStart(3, '0')}`,
    name: `${base.name} ${copyNumber}`,
    nameRu: `${base.nameRu} ${copyNumber}`,
    modifiedAt: modifiedAt.toISOString(),
    videoUrl: `${base.videoUrl}?variant=${copyNumber}`,
    previewImageUrl: `${base.previewImageUrl}?variant=${copyNumber}`,
  };
});

export const fetchExercises = ({
  name,
  cursor = 0,
  limit = 30,
}: FetchExercisesParams = {}): Promise<FetchExercisesResponse> => {
  const filtered = filterExercisesByName(mockExercises, name);
  const items = filtered.slice(cursor, cursor + limit);
  const nextCursor = cursor + limit < filtered.length ? cursor + limit : null;
  const result = {
    items,
    nextCursor,
    total: filtered.length,
  };

  return new Promise((resolve) => {
    setTimeout(() => resolve(result), MOCK_DELAY_MS);
  });
};

export const deleteExercises = ({ ids }: DeleteExercisesParams): Promise<DeleteExercisesResponse> =>
  new Promise((resolve) => {
    setTimeout(() => resolve({ deletedIds: ids }), MOCK_DELAY_MS);
  });

export const createExercise = (params: CreateExerciseParams): Promise<Exercise> => {
  const created: Exercise = {
    ...params,
    id: `ex-${Date.now()}`,
    addedBy: 'You',
    modifiedBy: 'You',
    modifiedAt: new Date().toISOString(),
  };
  mockExercises.unshift(created);

  return new Promise((resolve) => {
    setTimeout(() => resolve(created), MOCK_DELAY_MS);
  });
};
